os:
  - windows
  - linux
  - osx

env:
  - YARN_GPG=no # Fixes build on Windows

language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - jest --coverage --testPathIgnorePatterns test-app
  - yarn audit
  - cat ./coverage/lcov.info | coveralls
